In [1]:
import calendar
import matplotlib.pyplot as plt
from datetime import datetime
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import locale
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules,apriori
from scipy import sparse

In [2]:
df = pd.read_csv('sales_detail.csv')

In [3]:
# Convert Tipe Data
df['Price']=df['Price'].astype(int)

# Pre-processing Date.Time
locale.setlocale(locale.LC_TIME, 'id_ID')
df['Date'] = pd.to_datetime(df['Date'])
df['Waktu'] = pd.cut(df['Hour'], bins=[0, 12, 18, 24], labels=['Pagi', 'Siang', 'Malam'])
df['Hari'] = df['Date'].dt.day_name(locale= 'id_ID')
df['Bulan'] = df['Date'].dt.month_name(locale= 'id_ID')
df['Tahun'] = df['Date'].dt.year

# LabelEncoding
df['Receiveno'] = LabelEncoder().fit_transform(df['Receiveno'])

In [4]:
df.head()

,Date,Receiveno,Hour,Dept,Category,Sub Category,Type Product,Product Name,Qty,Price,Value,Waktu,Hari,Bulan,Tahun
0,2020-08-08,14835,13,CIGARETTE,CIGARETTE,KRETEK CIGARETTE HANDMADE (SKT),CIGARETTE,DJARUM COKLAT 12S,1,15000,15000,Siang,Sabtu,Agustus,2020
1,2020-08-24,17944,11,CIGARETTE,CIGARETTE,KRETEK CIGARETTE HANDMADE (SKT),CIGARETTE,DJARUM COKLAT 12S,1,15000,15000,Pagi,Senin,Agustus,2020
2,2020-09-06,21156,10,CIGARETTE,CIGARETTE,KRETEK CIGARETTE HANDMADE (SKT),CIGARETTE,DJARUM COKLAT 12S,1,15000,15000,Pagi,Minggu,September,2020
3,2020-06-01,17,10,CIGARETTE,CIGARETTE,KRETEK CIGARETTE HANDMADE (SKT),CIGARETTE,DJI SAM SOE MGNM PREM FILT 12S,1,19000,19000,Pagi,Senin,Juni,2020
4,2020-06-01,19,10,CIGARETTE,CIGARETTE,KRETEK CIGARETTE HANDMADE (SKT),CIGARETTE,DJI SAM SOE MGNM PREM FILT 12S,1,19000,19000,Pagi,Senin,Juni,2020

In [5]:
df['Product Name'].value_counts()

AQUA AIR MINERAL BTL 600 ML      1283
SAMPOERNA A MILD  16S             990
GG FILTER 12S                     946
TAC STEAMY HOT DOG 12 CM          776
FROSTER CHOCO 16 OZ               732
                                 ...
ABC KOPI SUSU BOX 5X32 GR           1
TRI AON 6GB                         1
TOR CD PRIA SEKALI PAKAI XL         1
CLEAR SHP. ICE MENTHOL 37X160       1
FS GULA PASIR KUNING 1KG            1
Name: Product Name, Length: 1134, dtype: int64

In [6]:
# df.isna().sum()

In [7]:
# df.isnull().sum()

In [8]:
df.dtypes

Date            datetime64[ns]
Receiveno                int32
Hour                     int64
Dept                    object
Category                object
Sub Category            object
Type Product            object
Product Name            object
Qty                      int64
Price                    int32
Value                    int64
Waktu                 category
Hari                    object
Bulan                   object
Tahun                    int64
dtype: object

In [9]:
# # Top 10 Produk Paling Laris

# plt.figure(figsize=(13,5))
# sns.set_palette('muted')

# sns.barplot(x = df["Product Name"].value_counts()[:10].index,
#             y = df["Product Name"].value_counts()[:10].values)
# plt.xlabel(""); plt.ylabel("")
# plt.xticks(size = 8, rotation = 90)
# plt.title('Top 10 Nama Produk Paling Laris',size = 15)

In [10]:
# df_bulan = df.groupby('Hari')['Receiveno'].count()
# df_bulan = pd.concat([df_bulan.iloc[4:], df_bulan.iloc[:4]])

# plt.figure(figsize=(7,4))
# sns.barplot(x = df['Hari'].unique(), y = df_bulan.values)

# plt.xticks(size = 10)
# plt.title('Total Transaksi Tiap Hari', size = 12)

In [11]:
# df_bulan = df.groupby('Bulan')['Receiveno'].count()
# df_bulan = pd.concat([df_bulan.iloc[4:], df_bulan.iloc[:4]])

# plt.figure(figsize=(7,4))
# sns.barplot(x = df['Bulan'].unique(), y = df_bulan.values)

# plt.xticks(size = 10)
# plt.title('Total Transaksi Tiap Bulan', size = 12)

In [12]:
# df_bulan = df.groupby('Waktu')['Receiveno'].count()
# df_bulan = pd.concat([df_bulan.iloc[4:], df_bulan.iloc[:4]])

# plt.figure(figsize=(7,4))
# sns.barplot(x = df['Waktu'].unique(), y = df_bulan.values)

# plt.xticks(size = 10)
# plt.title('Total Transaksi Tiap Waktu', size = 12)

In [13]:
# df_jam = df.groupby('Hour')['Receiveno'].count()

# plt.figure(figsize=(7,4))
# sns.barplot(x = df_jam.index, y = df_jam.values)

# plt.xticks(size = 10)
# plt.title('Total Transaksi Saat Toko Buka-Tutup Berdasarkan Jam', size = 12)

In [14]:
item_count_pivot = df.pivot_table(index='Receiveno',columns='Product Name', values= 'Qty',aggfunc='sum').fillna(0)
item_count_pivot[item_count_pivot > 0] =1
item_count_pivot.head(10)

Product Name,5 DAYS CROISSANT CHOCOLATE,5 DAYS CROISSANT MIXED BERRIES,5 DAYS CROISSANT PEANUT BUTTER,ABC ALKALINE LR-03 AAA-2S,ABC ALKALINE LR-03 AAA-4S,ABC ALKALINE LR-06 AA-2S,ABC ALKALINE LR-06 AA-4S,ABC BATTERY R-20 UM-I BIRU 2S,ABC BATTERY R-6 BIRU AA-4S,ABC KACANG HIJAU 250ML,...,YOFORIA ACTIV 8 170ML,YOU C-1000 LEMON BTL 140 ML,YOU C-1000 LMN WTR BTL 500 ML,YOU C-1000 ORANGE BTL 140 ML,YOU C-1000 ORANGE WTR BTL 500ML,YOU C-1000 VITAMIN APPLE 140 ML,YOUVIT DEWASA 7 DAY,YUPI GUMMY CANDIES MINI BUR,YUPI GUMMY CANDIES STRAWBER,ZIPPO LIGHTER FLUID - 125 ML
Receiveno,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
# Keterangan Olah Dataset
print('Dimensi Dataset :',item_count_pivot.shape)
print('Jumlah Transaksi :',item_count_pivot.shape[0])
print('Jumlah Barang :',item_count_pivot.shape[1])

Dimensi Dataset : (26083, 1134)
Jumlah Transaksi : 26083
Jumlah Barang : 1134

In [16]:
# Transformasi Data Sparse Matrix
te = TransactionEncoder()
te_ary = te.fit(item_count_pivot).transform(item_count_pivot)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [17]:
# # Tentukan nilai support yang akan diuji
# support_list = [0.001, 0.002, 0.003, 0.004, 0.005]

# # Tentukan ukuran frequent itemset yang diinginkan
# size = 2

# # Cari nilai support yang optimal
# optimal_support = None
# optimal_itemsets = None
# for support in support_list:
#     frequent_itemsets = apriori(df, min_support=support, use_colnames=True)
#     itemsets = frequent_itemsets[frequent_itemsets['itemsets'].apply(lambda x: len(x)) == size]
#     if len(itemsets) > 0:
#         optimal_support = support
#         optimal_itemsets = itemsets
#         break

# # Print hasil
# print('Optimal support:', optimal_support)
# print('Frequent itemsets:')
# print(optimal_itemsets)

In [18]:
freq = apriori(item_count_pivot, min_support= 0.001, use_colnames= True)
freq.sort_values('support',ascending=False).head()

c:\Users\LENOVO\AppData\Local\Programs\Python\Python310\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                       itemsets
10   0.049189  (AQUA AIR MINERAL BTL 600 ML)
263  0.037956        (SAMPOERNA A MILD  16S)
103  0.036269                (GG FILTER 12S)
294  0.029751     (TAC STEAMY HOT DOG 12 CM)
97   0.027988          (FROSTER CHOCO 16 OZ)

In [56]:
rules = association_rules(freq,metric='lift',min_threshold=1)[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by=['support','confidence','lift'],ascending=False)

,antecedents,consequents,support,confidence,lift
18,(FROSTER CHEESE MILK 16 OZ),(FROSTER CHOCO 16 OZ),0.010313,0.510436,18.237964
19,(FROSTER CHOCO 16 OZ),(FROSTER CHEESE MILK 16 OZ),0.010313,0.368493,18.237964
31,(FROSTER TROPICAL BLUE 16OZ),(FROSTER STRAWBERRY 16 OZ),0.007016,0.480315,24.759002
30,(FROSTER STRAWBERRY 16 OZ),(FROSTER TROPICAL BLUE 16OZ),0.007016,0.361660,24.759002
24,(FROSTER STRAWBERRY 16 OZ),(FROSTER CHOCO 16 OZ),0.005176,0.266798,9.532744
25,(FROSTER CHOCO 16 OZ),(FROSTER STRAWBERRY 16 OZ),0.005176,0.184932,9.532744
8,(BIMOLI KLASIK POUCH 2LT),(INDOMIE GORENG SPECIAL BAG 84GR),0.003911,0.944444,65.169165
9,(INDOMIE GORENG SPECIAL BAG 84GR),(BIMOLI KLASIK POUCH 2LT),0.003911,0.269841,65.169165
26,(FROSTER TROPICAL BLUE 16OZ),(FROSTER CHOCO 16 OZ),0.003527,0.241470,8.627750
27,(FROSTER CHOCO 16 OZ),(FROSTER TROPICAL BLUE 16OZ),0.003527,0.126027,8.627750
39,(INDOMIE GORENG SPECIAL BAG 84GR),(SAMPOERNA A MILD 16S),0.003297,0.227513,5.994169
38,(SAMPOERNA A MILD 16S),(INDOMIE GORENG SPECIAL BAG 84GR),0.003297,0.086869,5.994169
21,(FROSTER STRAWBERRY 16 OZ),(FROSTER CHEESE MILK 16 OZ),0.002837,0.146245,7.238159
20,(FROSTER CHEESE MILK 16 OZ),(FROSTER STRAWBERRY 16 OZ),0.002837,0.140417,7.238159
40,(INDOMIE SOTO MIE PACK),(SAMPOERNA A MILD 16S),0.002300,0.560748,14.773718
41,(SAMPOERNA A MILD 16S),(INDOMIE SOTO MIE PACK),0.002300,0.060606,14.773718
1,(5 DAYS CROISSANT MIXED BERRIES),(5 DAYS CROISSANT CHOCOLATE),0.002185,0.456000,42.027731
0,(5 DAYS CROISSANT CHOCOLATE),(5 DAYS CROISSANT MIXED BERRIES),0.002185,0.201413,42.027731
7,(BEAR BRAND EVAP MILK CAN 195ML),(INDOMIE GORENG SPECIAL BAG 84GR),0.001994,0.161491,11.143284
6,(INDOMIE GORENG SPECIAL BAG 84GR),(BEAR BRAND EVAP MILK CAN 195ML),0.001994,0.137566,11.143284
23,(FROSTER TROPICAL BLUE 16OZ),(FROSTER CHEESE MILK 16 OZ),0.001994,0.136483,6.754999
22,(FROSTER CHEESE MILK 16 OZ),(FROSTER TROPICAL BLUE 16OZ),0.001994,0.098672,6.754999
44,(SOSIS TUSUK JUMBO HOT),(SOSIS TUSUK BOLADO),0.001725,0.207373,22.822435
36,(MARLBORO RED 20S),(INDOMIE GORENG SPECIAL BAG 84GR),0.001725,0.199115,13.739465
45,(SOSIS TUSUK BOLADO),(SOSIS TUSUK JUMBO HOT),0.001725,0.189873,22.822435
49,(STMY HOT DOG HOT&SPCY),(TAC STEAMY HOT DOG 12 CM),0.001725,0.140625,4.726703
37,(INDOMIE GORENG SPECIAL BAG 84GR),(MARLBORO RED 20S),0.001725,0.119048,13.739465
48,(TAC STEAMY HOT DOG 12 CM),(STMY HOT DOG HOT&SPCY),0.001725,0.057990,4.726703
4,(TAC STEAMY HOT DOG 12 CM),(AQUA AIR MINERAL BTL 600 ML),0.001610,0.054124,1.100319
5,(AQUA AIR MINERAL BTL 600 ML),(TAC STEAMY HOT DOG 12 CM),0.001610,0.032736,1.100319
13,(CHOCO MILK),(TAC STEAMY HOT DOG 12 CM),0.001342,0.065056,2.186662
12,(TAC STEAMY HOT DOG 12 CM),(CHOCO MILK),0.001342,0.045103,2.186662
16,(FROSTER CHEESE MILK 12 OZ),(FROSTER CHOCO 12 OZ),0.001304,0.090426,3.702620
33,(INDOMIE GORENG SPECIAL BAG 84GR),(GG FILTER 12S),0.001304,0.089947,2.480011
17,(FROSTER CHOCO 12 OZ),(FROSTER CHEESE MILK 12 OZ),0.001304,0.053375,3.702620
32,(GG FILTER 12S),(INDOMIE GORENG SPECIAL BAG 84GR),0.001304,0.035941,2.480011
10,(LIGHTER CAMEL PURPLE),(CAMEL MILD OPTION PURPLE 12S),0.001189,1.000000,367.366197
11,(CAMEL MILD OPTION PURPLE 12S),(LIGHTER CAMEL PURPLE),0.001189,0.436620,367.366197
2,(SPUNBOND TAS POLOS),(AQUA AIR MINERAL BTL 600 ML),0.001189,0.077500,1.575551
3,(AQUA AIR MINERAL BTL 600 ML),(SPUNBOND TAS POLOS),0.001189,0.024162,1.575551
29,(FROSTER TROPICAL BLUE 12OZ),(FROSTER STRAWBERRY 12 OZ),0.001150,0.113208,8.388615
28,(FROSTER STRAWBERRY 12 OZ),(FROSTER TROPICAL BLUE 12OZ),0.001150,0.085227,8.388615
46,(SOSIS TUSUK BOLADO),(TAC STEAMY HOT DOG 12 CM),0.001112,0.122363,4.112875
47,(TAC STEAMY HOT DOG 12 CM),(SOSIS TUSUK BOLADO),0.001112,0.037371,4.112875
15,(DUNHILL FINE CUT FILTER 16S),(INDOMIE SOTO MIE PACK),0.001073,0.509091,124.099235
14,(INDOMIE SOTO MIE PACK),(DUNHILL FINE CUT FILTER 16S),0.001073,0.261682,124.099235
42,(PAO KACANG HIJAU),(PAO AYAM MERAH),0.001035,0.278351,71.178593
43,(PAO AYAM MERAH),(PAO KACANG HIJAU),0.001035,0.264706,71.178593
34,(LITE&BITE CHOCO-CHESEE),(GOLDA DOLCE LATTE 200ML),0.001035,0.101124,4.875428
35,(GOLDA DOLCE LATTE 200ML),(LITE&BITE CHOCO-CHESEE),0.001035,0.049908,4.875428

In [54]:
rules[['antecedents', 'consequents']]

                          antecedents                        consequents
0        (5 DAYS CROISSANT CHOCOLATE)   (5 DAYS CROISSANT MIXED BERRIES)
1    (5 DAYS CROISSANT MIXED BERRIES)       (5 DAYS CROISSANT CHOCOLATE)
2                (SPUNBOND TAS POLOS)      (AQUA AIR MINERAL BTL 600 ML)
3       (AQUA AIR MINERAL BTL 600 ML)               (SPUNBOND TAS POLOS)
4          (TAC STEAMY HOT DOG 12 CM)      (AQUA AIR MINERAL BTL 600 ML)
5       (AQUA AIR MINERAL BTL 600 ML)         (TAC STEAMY HOT DOG 12 CM)
6   (INDOMIE GORENG SPECIAL BAG 84GR)   (BEAR BRAND EVAP MILK CAN 195ML)
7    (BEAR BRAND EVAP MILK CAN 195ML)  (INDOMIE GORENG SPECIAL BAG 84GR)
8           (BIMOLI KLASIK POUCH 2LT)  (INDOMIE GORENG SPECIAL BAG 84GR)
9   (INDOMIE GORENG SPECIAL BAG 84GR)          (BIMOLI KLASIK POUCH 2LT)
10             (LIGHTER CAMEL PURPLE)     (CAMEL MILD OPTION PURPLE 12S)
11     (CAMEL MILD OPTION PURPLE 12S)             (LIGHTER CAMEL PURPLE)
12         (TAC STEAMY HOT DOG 12 CM)                       (CHOCO MILK)
13                       (CHOCO MILK)         (TAC STEAMY HOT DOG 12 CM)
14            (INDOMIE SOTO MIE PACK)      (DUNHILL FINE CUT FILTER 16S)
15      (DUNHILL FINE CUT FILTER 16S)            (INDOMIE SOTO MIE PACK)
16        (FROSTER CHEESE MILK 12 OZ)              (FROSTER CHOCO 12 OZ)
17              (FROSTER CHOCO 12 OZ)        (FROSTER CHEESE MILK 12 OZ)
18        (FROSTER CHEESE MILK 16 OZ)              (FROSTER CHOCO 16 OZ)
19              (FROSTER CHOCO 16 OZ)        (FROSTER CHEESE MILK 16 OZ)
20        (FROSTER CHEESE MILK 16 OZ)         (FROSTER STRAWBERRY 16 OZ)
21         (FROSTER STRAWBERRY 16 OZ)        (FROSTER CHEESE MILK 16 OZ)
22        (FROSTER CHEESE MILK 16 OZ)       (FROSTER TROPICAL BLUE 16OZ)
23       (FROSTER TROPICAL BLUE 16OZ)        (FROSTER CHEESE MILK 16 OZ)
24         (FROSTER STRAWBERRY 16 OZ)              (FROSTER CHOCO 16 OZ)
25              (FROSTER CHOCO 16 OZ)         (FROSTER STRAWBERRY 16 OZ)
26       (FROSTER TROPICAL BLUE 16OZ)              (FROSTER CHOCO 16 OZ)
27              (FROSTER CHOCO 16 OZ)       (FROSTER TROPICAL BLUE 16OZ)
28         (FROSTER STRAWBERRY 12 OZ)       (FROSTER TROPICAL BLUE 12OZ)
29       (FROSTER TROPICAL BLUE 12OZ)         (FROSTER STRAWBERRY 12 OZ)
30         (FROSTER STRAWBERRY 16 OZ)       (FROSTER TROPICAL BLUE 16OZ)
31       (FROSTER TROPICAL BLUE 16OZ)         (FROSTER STRAWBERRY 16 OZ)
32                    (GG FILTER 12S)  (INDOMIE GORENG SPECIAL BAG 84GR)
33  (INDOMIE GORENG SPECIAL BAG 84GR)                    (GG FILTER 12S)
34           (LITE&BITE CHOCO-CHESEE)          (GOLDA DOLCE LATTE 200ML)
35          (GOLDA DOLCE LATTE 200ML)           (LITE&BITE CHOCO-CHESEE)
36                 (MARLBORO RED 20S)  (INDOMIE GORENG SPECIAL BAG 84GR)
37  (INDOMIE GORENG SPECIAL BAG 84GR)                 (MARLBORO RED 20S)
38            (SAMPOERNA A MILD  16S)  (INDOMIE GORENG SPECIAL BAG 84GR)
39  (INDOMIE GORENG SPECIAL BAG 84GR)            (SAMPOERNA A MILD  16S)
40            (INDOMIE SOTO MIE PACK)            (SAMPOERNA A MILD  16S)
41            (SAMPOERNA A MILD  16S)            (INDOMIE SOTO MIE PACK)
42                 (PAO KACANG HIJAU)                   (PAO AYAM MERAH)
43                   (PAO AYAM MERAH)                 (PAO KACANG HIJAU)
44            (SOSIS TUSUK JUMBO HOT)               (SOSIS TUSUK BOLADO)
45               (SOSIS TUSUK BOLADO)            (SOSIS TUSUK JUMBO HOT)
46               (SOSIS TUSUK BOLADO)         (TAC STEAMY HOT DOG 12 CM)
47         (TAC STEAMY HOT DOG 12 CM)               (SOSIS TUSUK BOLADO)
48         (TAC STEAMY HOT DOG 12 CM)            (STMY HOT DOG HOT&SPCY)
49            (STMY HOT DOG HOT&SPCY)         (TAC STEAMY HOT DOG 12 CM)